import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Button } from "@/components/ui/button";
import { Menu, User } from "lucide-react";
import { cookies } from "next/headers";
import { logoutAction } from "@/lib/actions";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = (await cookies()).get("token")?.value;
  return (
    <html lang="en">
      <body className={`${geistSans.className}  antialiased`}>
        {token && (
          <header className="border-b bg-[#0c3b5a] text-white">
            <div className="flex h-14 items-center px-4">
              <Button variant="ghost" size="icon" className="mr-2 text-white">
                <Menu className="h-5 w-5" />
                <span className="sr-only">Menu</span>
              </Button>
              <div className="flex items-center">
                <span className="text-lg font-semibold">ANS IT INDIA</span>
              </div>
              <div className="ml-auto flex items-center ">
                <Button className="text-white" onClick={logoutAction}>
                  Logout
                </Button>
              </div>
            </div>
          </header>
        )}
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
